name: Build and Deploy to Cloud Run

on:
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-west1
  SERVICE_NAME: simple

jobs:
  setup-build-deploy:
    name: Just Build docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        docker build --tag=gcr.io/$PROJECT_ID/simple:latest --file=./Dockerfile .